"""
Synthesizer Node — Combines parallel agent outputs into a unified response
with citations and educational disclaimers.
"""

from langchain_core.messages import SystemMessage, HumanMessage
from langchain_openai import ChatOpenAI

from src.core.config import CONFIG, OPENAI_API_KEY
from src.workflow.state import FinanceAssistantState

PRIMARY_MODEL = CONFIG.get("models", {}).get("primary_model", "gpt-4o")

SYNTHESIZER_SYSTEM_PROMPT = """You are the Chief Editor and Response Synthesizer for the AI Finance Assistant.
Your task is to review the results generated by one or more specialist domain agents and assemble a coherent, professional response.

SYNTHESIS GUIDELINES:
1. Single Agent result: Clean up formatting, preserve citation references (e.g. [ref: INV-001]), and present directly.
2. Multiple Agent results: Merge the information smoothly under clear Markdown section headings. Remove redundant introductory fluff or repeated greetings across agent outputs.
3. Citations: Maintain any reference IDs (e.g., [ref: INV-001], [ref: TAX-001]).
4. Compliance: Always append a concise footer disclaimer on a new line:
   `---`
   `*Disclaimer: This information is for educational purposes only and does not constitute financial, investment, or tax advice.*`
"""


def synthesizer_node(state: FinanceAssistantState) -> dict:
    results = state.get("agent_results", [])
    if not results:
        return {
            "final_answer": "I apologize, but I could not generate an answer for your query. Please try rephrasing."
        }

    # If single result, format cleanly with disclaimer
    if len(results) == 1:
        res_text = results[0].get("result", "")
        disclaimer = "\n\n---\n*Disclaimer: This information is for educational purposes only and does not constitute financial, investment, or tax advice.*"
        return {"final_answer": f"{res_text}{disclaimer}"}

    # Parallel synthesis pass
    llm = ChatOpenAI(model=PRIMARY_MODEL, temperature=0.1, api_key=OPENAI_API_KEY)
    combined_inputs = "\n\n".join(
        f"### Result from {r.get('agent')}:\n{r.get('result')}" for r in results
    )

    messages = [
        SystemMessage(content=SYNTHESIZER_SYSTEM_PROMPT),
        HumanMessage(content=f"User Query: {state.get('user_query')}\n\nAgent Findings:\n{combined_inputs}")
    ]

    final_resp = llm.invoke(messages)
    return {"final_answer": final_resp.content}